name: "Learn GitHub Actions"
run-name: "The second lesson of the Github Actions workflow course"
on: [push, push, pull_request]
concurrency: my-workflow
env:
  MY_NAME: "Łukasz"
  AGE: 35
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - run: npm install -g bats
      - run: bats -v
      - run: echo "Hello ${{ env.MY_NAME }} and you are ${{ env.AGE }} years old"